"""migrations

Revision ID: 1e4340abff96
Revises: 32614ac215bc
Create Date: 2025-05-25 23:16:49.646387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e4340abff96"
down_revision: Union[str, None] = "32614ac215bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ingredient_transactions",
        "transaction_type",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Enum(
            "IN", "OUT", name="transaction_type_enum", create_constraint=True
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ingredient_transactions",
        "transaction_type",
        existing_type=sa.Enum(
            "IN", "OUT", name="transaction_type_enum", create_constraint=True
        ),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
